# This is a basic workflow to help you get started with Actions

name: CI v2 Publish to Registry

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build_Docker_Image:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - id: pre-step
      shell: bash
      run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
    - name: Publish Docker to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: cbkennedy/tictactoe
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ steps.pre-step.outputs.release-version }}"
